### ISSUE TITLE
Data loss on conversion from uint64 > string > uint64

### ISSUE THREAD

**Issue by antonio-alexander** [pip-services3-go/pip-services3-commons-go#1]
I found that my filter functions were failing when I attempted to filter using ids that were sufficiently large. I found that when I had an input (via tuples) of a uint64 of 16030862614303175036, the string conversion would store an incorrect value in the StringValueMap of "-2415881459406376580". I think the issue is specific to the string converter for uint64 values that would overflow int64s.

This may help (totally untested):
`
writeTagID := uint64(16030862614303175036)
m := NewEmptyStringValueMap()
m.SetAsObject("tag_id", writeTagID )
readTagID := m.GetAsObject("tag_id").(uint64)
fmt.Println(readTagID)
fmt.Println(writeTagID)
`

Unsolicited opinion: I'm sure there's a reason why you store the data as a string rather than the data type (simple serialization maybe), but specifically for the filters it may make sense to take out that layer altogether. Filters will generally always be in the critical path for C**R**UD operations and swapping the types under the hood is unnecessary when the person implementing the service has very clear idea of the data going in and the data going out (and can perform their own conversions). I don't think there's a practical use case where someone would implement a filter and NOT know the data types on both ends.

**Comment by levichevdmitry** [comment]
Bug fixed in new release v1.1.1
Please, use specific methods for convert to unsigned values (ToULong, ToUInteger, etc.).
Thanks!
